apiVersion: v1
kind: Service
metadata:
  name: drone
  labels:
    app: drone
spec:
  type: ClusterIP
  selector:
    app: drone
  ports:
  - name: http
    port: 8000
    protocol: TCP
  - name: agent
    port: 9000
    protocol: TCP