apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oklog
  labels:
    app: oklog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: oklog
        app: oklog
    spec:
      containers:
      - name: oklog
        image: oklog/oklog
        imagePullPolicy: Always
        ports:
        - name: api
          containerPort: 7650
        - name: ingest-fast
          containerPort: 7651
        - name: ingest-durable
          containerPort: 7652
        - name: ingest-bulk
          containerPort: 7653
        - name: cluster
          containerPort: 7659
        args:
        - ingeststore
        - -store.segment-replication-factor
        - "1"
        - -store.path
        - /data/store
        - -ingest.path
        - /data/ingest
        volumeMounts:
        - name: oklog-data
          mountPath: /data
      volumes:
      - name: oklog-data
        hostPath:
          path: /data/logging/