apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexcloud
  annotations:
    ingress.kubernetes.io/config-backend: |
      acl ios_carddav path_beg /.well-known/carddav
      acl ios_caldav path_beg /.well-known/caldav    
      http-response set-header Referrer-Policy strict-origin
      http-request redirect location https://cloud.nfsmith.ca/remote.php/dav if ios_carddav
      http-request redirect location https://cloud.nfsmith.ca/remote.php/dav if ios_caldav
spec:
  tls:
  - hosts:
    - cloud.nfsmith.ca
    secretName: tls-certs
  rules:
  - host: cloud.nfsmith.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80