apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-mariadb
  labels:
    app: nc-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nc-mariadb
  template:
    metadata:
      labels:
        app: nc-mariadb
    spec:
      containers:
      - name: nc-mariadb
        image: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: root-password 
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: password
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-vol
      volumes:
      - name: mariadb-vol
        hostPath:
          path: /data/nextcloud/database
          type: DirectoryOrCreate