apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
spec:
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailserver
        image: hardware/mailserver:1.1-stable
        imagePullPolicy: Always
        env:
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: mailserver
              key: dbpass
        - name: RSPAMD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mailserver
              key: rspamdpass
        - name: FQDN
          value: mail.nfsmith.ca
        - name: DOMAIN
          value: mail.nfsmith.ca
        ports:
        - containerPort: 25
          hostPort: 25
        - containerPort: 143
          hostPort: 143
        - containerPort: 587
          hostPort: 587
        - containerPort: 993
          hostPort: 993
        - containerPort: 4190
          hostPort: 4190
        volumeMounts:
          - name: data
            mountPath: "/var/mail"
      volumes:
      - name: data
        hostPath:
          path: /data/email/mailbox
          type: DirectoryOrCreate
