apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
spec:
  selector:
    matchLabels:
      app: postfixadmin
  template:
    metadata:
      labels:
        app: postfixadmin
    spec:
      containers:
      - name: postfixadmin
        image: hardware/postfixadmin
        env:
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: mailserver
              key: dbpass
        - name: FQDN
          value: nfsmith.ca
        - name: DOMAIN
          value: nfsmith.ca
        ports:
        - containerPort: 8888

